### ISSUE TITLE
Remove the use of `nothing` to designate non-differentiability in `rrule_test`

### ISSUE THREAD

**Issue by mzgubic** [JuliaDiff/ChainRulesTestUtils.jl#113]
Reusing similar example as in #112:
```julia
function partly_dne(a, i)
    return a[i]
end

function ChainRulesCore.rrule(::typeof(partly_dne), a, i)
    y = partly_dne(a, i)
    function partly_dne_pullback(ȳ)
        grad = zeros(size(a))
        grad[i] = ȳ
        return (NO_FIELDS, grad, DoesNotExist())
    end
    return y, partly_dne_pullback
end
```
It seems un `ChainRules` like that `nothing` should be used instead of `DoesNotExist()`. Should we change this for v1?
```
julia> rrule_test(partly_dne, rand(), (rand(4), rand(4)), (1, nothing))

**Comment by oxinabox** [comment]
@willtebbutt  thoughts?

**Comment by oxinabox** [comment]
If we can do this, then we will likely be able to get rid of a lot of `k ⊢ nothing` as the `rand_tangent(k)` will in many cases return `DoesNotExist()`

**Comment by mzgubic** [comment]
needs the deprecation removed in v1
