### ISSUE TITLE
*rule_test should take a frule_like/rrule_like function so we can test AD systems

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRulesTestUtils.jl#114]
In order to make `frule_test` and `rrule_test` more generally useful for testing AD systems,
we should make them take a keyword argument that specifies what function that what to use.
This function would be used in the place of the default `frule`/`rrule`.

It would need to match the API of `frule` and `rrule`.
Just like the function that needs to be provided for https://github.com/JuliaDiff/ChainRulesCore.jl/issues/68

Then we would be able to use these tools to test AD systems

**Comment by willtebbutt** [comment]
@oxinabox do you recall if this is included in ADIA? @matbesancon also requested it in #125 , and I keep realising that I need it when I want to check that AD is doing the right thing for a function that I particularly care about, even if I've not written any new rules.

**Comment by mzgubic** [comment]
I don't think it is, but we can probably add it - I have only considered this superficially but it doesn't seem like a huge task?

**Comment by willtebbutt** [comment]
Yeah, it really shouldn't be too large a task.

My opinion is that we should limit the scope such that we require whatever function is passed to have the same API as `frule`/ `rrule`, and its the responsibility of whoever is calling the tests to ensure that this is satisfied. I think that would already put us in a pretty good place.
