### ISSUE TITLE
Function for comparison of manual gradients with finite diffs

### ISSUE THREAD

**Issue by matbesancon** [JuliaDiff/ChainRulesTestUtils.jl#125]
Would it be in scope for the package to add a verification for manual gradients, something like:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.check_grad.html

Could be useful for gradients beyond ChainRules. It could wrap the existing methods building JVP and VJPs

**Comment by willtebbutt** [comment]
Yes. Would [this](https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/114) be sufficient?

**Comment by matbesancon** [comment]
yes perfectly, I didn't catch the other issue, I'll close this as duplicate then

**Comment by willtebbutt** [comment]
Excellent :)
