### ISSUE TITLE
Test all kinds of tangent types (Thunk, ZeroTangent, Tangent{T} etc)

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRulesTestUtils.jl#159]
This is a generalization of #98  and is a key part of https://github.com/JuliaDiff/ChainRules.jl/issues/408

Lets say we have a tanget `dx`
  we should also test that in it's place we can put `@thunk(x̄)`, as well as `ZeroTangent`.

Further, following https://github.com/JuliaDiff/ChainRulesCore.jl/issues/286
if `dx <: AbstractArray` (other than `Array`) we should test `canonicalize(Composite{typeof(x)}, dx)`
and conversely
if `dx <: Composite{P} where P<:AbstractArray` we should test `canonicalize(P, dx)`

**Comment by mzgubic** [comment]
Just to confirm: for `test_rrule` we just want to change the `output_tangent`, and not the cotangents of the `args`, right?

And conversely, for `test_frule`, we just want the tangents of the `args`, and not the tangent of the output?

**Comment by mzgubic** [comment]
Also, the current implementation I have in mind is something like
```julia
function test_rrule(f, args; output_tangent=Auto(), test_other_tangents=true; other_kwargs...)
    y = func(xs...; fkwargs...)
    ȳ = output_tangent isa Auto ? rand_tangent(y) : output_tangent
    if test_other_tangents
        for ybar in _all_possible_tangents(ȳ)
            test_rrule(f, args; output_tangent=ybar, test_other_tangents=false, other_kwargs...)
        end
    else
        do_the_current_thing()
    end
end
    
```
It's kind of ugly, do we have other ideas?

**Comment by oxinabox** [comment]
> Just to confirm: for test_rrule we just want to change the output_tangent, and not the cotangents of the args, right?
> And conversely, for test_frule, we just want to change the tangents of the args, and not the tangent of the output?

This is correct

> One other point is that requiring new output_tangent to pass the tests is a breaking change. I was initially planning to do this in two parts, i.e. adding ZeroTangents and thunks first, and adding canonicalize once we figure out the arrays.

Two parts sounds better.
Yes it means multiple rounds of breaking changes, but it is ChainRulesTestUtils so it is only a test dependency.

Potentially we can do something like what we have like we do for inference and have it's default controlled by a global?
That way we can start to roll it out for ChainRules.jl then once we have it all working and are happy with it we can change the default and tag a breaking release.

Possibly rather than a bool we want a typed object, for extensibility.
Probable fine in kwarg position, where it can then be used in dispatch for a function that is called that makes it positional

**Comment by mzgubic** [comment]
Thanks for reviewing
> Potentially we can do something like what we have like we do for inference and have it's default controlled by a global?

Could you elaborate please?

**Comment by mzgubic** [comment]
This is somewhat more involved than I hoped. The easiest thing to do would be to:
```julia
const DEFAULT_ALT_TANGENTS = Ref{Any}([])

function test_rrule(f, args; output_tangent=Auto(), other_tangents=DEFAULT_ALT_TANGENTS; other_kwargs...)
    for ybar in other_tangents
        test_rrule(f, args; output_tangent=ybar, test_other_tangents=[], other_kwargs...)
    end
    do_the_current_thing()
end
```

But that would prevent us from doing `canonicalize` on the `output_tangent` later. I.e. if the `output_tangent` is a `BlockDiagonal`, we want to test the `Tangent{BlockDiagonal}` tangent as well.

To do that, we need something like passing functions:
```julia
const DEFAULT_ALT_TANGENTS = Ref{Function}([x -> canonicalize(x), x -> @thunk(x), x -> ZeroTangent()])

function test_rrule(f, args; output_tangent=Auto(), other_tangents=DEFAULT_ALT_TANGENTS; other_kwargs...)
    y = func(xs...; fkwargs...)
    ȳ = output_tangent isa Auto ? rand_tangent(y) : output_tangent
    for make_other_ȳ in other_tangents
        test_rrule(f, args; output_tangent=make_other_ȳ(ȳ), test_other_tangents=[], other_kwargs...)
    end
    do_the_current_thing()
end
```
Also it looks like we will need [`project`](https://github.com/JuliaDiff/ChainRulesCore.jl/pull/306) before we can implement `ZeroTangent()` as an other differential (for the purpose of finite differencing).

**Comment by oxinabox** [comment]
I am not sure how much we need to actually finite difference test all these.
Or if some other tests would be fine.
Like checking if all inputs are ZeroTangent we get something that `iszero`

**Comment by oxinabox** [comment]
We are now happy enough with this, just testing Thunk.
Since pullback only has 1 input, we don't actually need that to be handled by the pullback -- it can be handled by the AD.
If pulling back a Tangent, I we could be doing transforms of that in interesting ways, but it seels a lot for little gain.

For trying structural vs natural differentials, we now have a fairly strong push towards never do structural if there is a good natural.
So testing both seems like it is not needful at this time. I suspect we we will not be seeing structural differentials for things with natural differentials very often.

We might want more for forwards mode later but that will be nonbreaking, since we will just be asserting things that had to be true in well-behaved code.

So I am going to call this done.
We can open new issues in the future
