### ISSUE TITLE
Overload `FiniteDifferences.to_vec` for Composite

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRulesTestUtils.jl#24]
needed for https://github.com/JuliaDiff/ChainRules.jl/pull/175

**Comment by oxinabox** [comment]
writing the `to_vec` for `Composite` of a struct is fiddly.
Since fields might be in a different order and some might be missing.

I think easiest is probably to use `canonicalize` to force everything into some fields and order as the primal type, and fill in any zeros.
Though that also means assing support for `Zero` so many not?


Luckily once we solve `to_vec` we solve `isapprox` basically for free.

**Comment by nickrobinson251** [comment]
alternative proposal that would make this redundant https://github.com/JuliaDiff/FiniteDifferences.jl/issues/97
(the intention is to do that, instead of overloading `to_vec`)

**Comment by nickrobinson251** [comment]
xref https://github.com/JuliaDiff/FiniteDifferences.jl/issues/105
