### ISSUE TITLE
Allow editing of `testset` name.

### ISSUE THREAD

**Issue by theogf** [JuliaDiff/ChainRulesTestUtils.jl#272]
The automatic testset naming is pretty nice but can also be cumbersome when passing heavily parametrized functions.
In my case (no MWE here sorry) it breaks the whole display.
Would you be open to a PR adding a `testset_name` kwarg to override the automatic one?

**Comment by oxinabox** [comment]
I think that would make sense.
So if you pass nothing it falls back to the default?

**Comment by theogf** [comment]
Yes exactly, so this would just be an opt-in thing.
