### ISSUE TITLE
Testing functions with symbols as arguments

### ISSUE THREAD

**Issue by sethaxen** [JuliaDiff/ChainRulesTestUtils.jl#30]
This came up in https://github.com/JuliaDiff/ChainRules.jl/pull/182, where `rrule_test` fails because one of the args equals `:U`. `_make_fdm_call` seems to evaluate that argument as a variable `U`, which does not exist.

**Comment by oxinabox** [comment]
Yeah, we need to get rid of the `eval` from there.

It's terrifying.

I found a note somewhere explaining why that was done. I think it was working around awkwardness in FiniteDifferences.jl
