### ISSUE TITLE
broken docs link in the readme

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaDiff/ChainRulesTestUtils.jl#49]

**Comment by willtebbutt** [comment]
Ah, yes, this package is very poorly documented. We should do something about that.

**Comment by mzgubic** [comment]
This has been fixed a while ago

**Comment by nickrobinson251** [comment]
`stable` badge still gives 404 for me, at https://juliadiff.org/ChainRulesTestUtils.jl/stable

**Comment by mzgubic** [comment]
Both seem to work now
