### ISSUE TITLE
Move meta testing utilities into a new MetaTesting.jl package

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRulesTestUtils.jl#62]
A follow-up to https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/60/
we could make a new package in [JuliaTesting](https://github.com/JuliaTesting/) called MetaTesting.jl to hold things like the function that captures all failures.

**Comment by sethaxen** [comment]
I recently needed these meta testers for another package, so I'd like to take the initiative to put this package together and register it.

**Comment by sethaxen** [comment]
Package created here: https://github.com/sethaxen/MetaTesting.jl. Will hold off on registering for a few days in case there are requested changes.

**Comment by nickrobinson251** [comment]
oh cool, I also recently wanted this! I used it for https://github.com/JuliaTesting/ReTestItems.jl/blob/main/test/_integration_test_tools.jl
think i might have needed to make some tweaks, but yeah if this was it's own package that sounds good to me

**Comment by sethaxen** [comment]
> think i might have needed to make some tweaks, but yeah if this was it's own package that sounds good to me

Nice! Seems you replaced `errors` (checks that the tester errors) with `errors` (returns the number of errors thrown during testing), which makes sense. I proposed in https://github.com/sethaxen/MetaTesting.jl/issues/1 that `errors` and `fails` are not very good names, and it might be better to add macros `@test_fails expr` and `@test_errors expr` to make it clearer and also simplify the syntax. Your functions also seem useful to add.

**Comment by nickrobinson251** [comment]
yeah, sounds good -- thanks for making the package! -- i'll go open some feature requests there 😁

**Comment by oxinabox** [comment]
@sethaxen  will you open the PR here to switch us over to using the MetaTesting.jl package?

**Comment by sethaxen** [comment]
> @sethaxen will you open the PR here to switch us over to using the MetaTesting.jl package?

Absolutely!
