### ISSUE TITLE
Remove automatic `extern` in `isapprox`?

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaDiff/ChainRulesTestUtils.jl#7]
This may be the same issue as "do we want `extern` at all?" (https://github.com/JuliaDiff/ChainRulesCore.jl/issues/56)

But I think if we have it, we may need it to be "smarter" if we're going to have `isapprox(a::Differential, b) = isapprox(extern(a), b)` as we currently do.

Because we will need to `extern(a)` (or maybe just `unthunk`?) the differential type _before_ calling `isapprox` anyway if `a` it is not a scalar (e.g. the `Zero` Matix case in SVD tests: https://github.com/JuliaDiff/ChainRules.jl/blob/8c4985a9a941df165740badfbee83cdf93661742/test/rulesets/LinearAlgebra/factorization.jl#L20-L22)

**Comment by nickrobinson251** [comment]
we also call `extern` manually before `isapprox` in `frule_test`

**Comment by nickrobinson251** [comment]
#20 changes this to only have methods on `AbstractThunk` and `AbstractZero`s

**Comment by oxinabox** [comment]
> we also call extern manually before isapprox in frule_test

I am inclined towards this and am infact doing it as part of solving #56 .
because `isapprox` on thunks gives error messages that don't include the numbers i need to see what is wrong.
