### ISSUE TITLE
rrule_test requires returned composite objects to be collectable

### ISSUE THREAD

**Issue by Kolaru** [JuliaDiff/ChainRulesTestUtils.jl#74]
`rrule_test` use `collect` to get the field of composite objects, but it is not always possible, as for e.g. `qr`

```
F = qr(randn(5, 5))
Q, R = F  # Valid since F is iterable
collect(F)  # Errors since length is not defined on LinearAlgebra.QRCompactWY
```

Using `[y...]` instead of `collect(y)` should do the trick.

**Comment by oxinabox** [comment]
Which `collect` in particular is a problem?
Several of them should go away once we do #57

**Comment by Kolaru** [comment]
Theses ones:

https://github.com/JuliaDiff/ChainRulesTestUtils.jl/blob/6f5cd3f7f1e1af78281e3dbae5882e16ecbe2d99/src/testers.jl#L235

**Comment by oxinabox** [comment]
Yep that one will go away when we do #57 right

**Comment by nickrobinson251** [comment]
Did removing the `collect` calls (in https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/57) resolve this?

**Comment by oxinabox** [comment]
yes
