### ISSUE TITLE
Composites + rrule_test

### ISSUE THREAD

**Issue by willtebbutt** [JuliaDiff/ChainRulesTestUtils.jl#80]
Currently, if you run `rrule_test` on something like the example below, `FiniteDifferences` makes its estimate of the cotangent of `x` an `Adjoint`, rather than a `Composite`. This isn't desirable behaviour in general, so we might want to consider providing an escape hatch in `FiniteDifferences` that lets us provide a function to get the cotangent of `x` from its vector-form, and utilising that escape hatch in this package to enable the user to provide the correct form of the cotangent, or to insist that `FiniteDifferences` uses a `to_vec` that is derived from an appropriate cotangent.

Example:
```julia
rrule(parent, randn(5, 3), (randn(5, 3)', Composite(parent=randn(5, 3)))
```

**Comment by oxinabox** [comment]
I think we are sorted now
open new issue, if still open
