### ISSUE TITLE
Make naming consistent: rename `test_scalar` or `frule_test`+`rrule_test`

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaDiff/ChainRulesTestUtils.jl#96]
We have `frule_test` for `frule`s, `rrule_test` for `rrule`... but `test_scalar` for `@scalar_rule` created rules.

I think it'd be easier to remember these names if we were consistent on whether  we used the suffix `_test` or the prefix `test_`.

Either (a) rename `test_scalar` -> `scalar_test` (or `scalar_rule_test`)
Or (b) rename `frule_test` -> `test_frule` and `rrule_test` -> `test_rrule`

Renaming is breaking, and that's annoying, but we may want to consider doing it for a v1.0 of this package?

**Comment by mzgubic** [comment]
Going with `test_frule` and `test_frule` would be consistent with the other test suite tools e.g. `@test_throws`, `@test_logs`, etc. where `test` is always first.

**Comment by nickrobinson251** [comment]
also `check_equal` -> `test_approx`

**Comment by mzgubic** [comment]
https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/116

**Comment by nickrobinson251** [comment]
> also `check_equal` -> `test_approx`

Was this decided against?

**Comment by mzgubic** [comment]
Oh, I missed that bit completely. I don't think we have reached conclusion on that. Will just reopen this one

**Comment by nickrobinson251** [comment]
ah cool, didn't know if i'd jsut missed that decision. 

yeah, seems easy to miss in this issue - made a new one 

https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/134

thanks <3
